// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_T_OA4gTm5xj0cQR8qRoJnbmzPVYmUn8',
    appId: '1:383107636759:web:ca240fe133866bba630652',
    messagingSenderId: '383107636759',
    projectId: 'recipe-app-4c007',
    authDomain: 'recipe-app-4c007.firebaseapp.com',
    storageBucket: 'recipe-app-4c007.appspot.com',
    measurementId: 'G-X1KP52HR3W',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIwO0gsTMXS8gyBVKnCRlnPdig41mR3yw',
    appId: '1:383107636759:ios:37ef59acef706bb4630652',
    messagingSenderId: '383107636759',
    projectId: 'recipe-app-4c007',
    storageBucket: 'recipe-app-4c007.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIwO0gsTMXS8gyBVKnCRlnPdig41mR3yw',
    appId: '1:383107636759:ios:b75f053587a81fc2630652',
    messagingSenderId: '383107636759',
    projectId: 'recipe-app-4c007',
    storageBucket: 'recipe-app-4c007.appspot.com',
    iosBundleId: 'com.example.recipeApp.RunnerTests',
  );
}
